services:
  test:
    &default
    container_name: golang_app
    image: golang:1.24-alpine
    working_dir: /app
    command: sh -c "go test -v ./..."
    environment:
      CGO_ENABLED: 0
      GOOS: linux
      REDIS_HOST: redis
      MEMCACHE_HOST: memcache

    volumes:
      - .:/app
      - godir:/go
    ports:
      - 8888:8888
    depends_on:
      - redis
      - memcache

  app:
    <<: *default
    container_name: golang_app
    command: go run main.go

  redis:
    image: redis:latest
    ports:
      - 6379:6379

  memcache:
    image: memcached:latest
    ports:
      - 11211:11211

volumes:
  godir: {}
