version: "3.7"

services:
  test:
    &default
    container_name: golang_app
    image: golang:1.18-alpine
    working_dir: /app
    command: sh -c "go test -v ./..."
    environment:
      - CGO_ENABLED=0
      - GOOS=linux
    volumes:
      - .:/app
      - godir:/go
    ports:
      - 8888:8888
    depends_on:
      - redis
      - memcache

  app:
    <<: *default
    container_name: golang_app
    command: go run main.go

  redis:
    image: redis
    ports:
      - 6379:6379

  memcache:
    image: memcached:1.4.21
    ports:
      - 11211:11211

networks:
  default:
    name: gritzkoo-golang-health-checker

volumes:
  godir: {}
