name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup golang
        uses: actions/setup-go@v1
        with:
          go-version: "1.22"
      - name: build package
        env:
          CGO_ENABLED: 0
          GOOS: linux
        run: |
          go mod tidy
          go build -a -installsuffix cgo -o entrypoint
