name: test
on: [push, pull_request]
jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        redis-version: [4, 5, 6]
        go: ["1.14", "1.15", "1.16", "1.17", "1.18"]
    steps:
      - uses: actions/checkout@v2
      - name: Sets up a Memcached server
        uses: niden/actions-memcached@v7
      - name: Start Redis
        uses: supercharge/redis-github-action@1.1.0
        with:
          redis-version: ${{ matrix.redis-version }}
      - uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - run: go test -v -coverprofile=profile.cov ./...

      - name: Send coverage to coverall.io
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: profile.cov
          flag-name: Go-${{ matrix.go }}
          parallel: true
          # notifies that all test jobs are finished.

  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: shogo82148/actions-goveralls@v1
        with:
          parallel-finished: true

  release-on-push:
    runs-on: ubuntu-latest
    needs:
      - test
      - finish
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: patch
